
  command = "npm run build"
  publish = "out" # This should be the directory where Next.js build files are generated


  NODE_VERSION = "14" # Use the appropriate Node.js version


  framework = "nextjs"

